# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'

target 'TesteConcrete-MVC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Cartography'
  pod 'Kingfisher'

  target 'TesteConcrete-MVCTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'KIF/IdentifierTests'

  end

end
